name: Docker Build Template

on:
  workflow_call:
    inputs:
      push:
        type: boolean
        required: true
      tag:
        type: string
        required: false
      platforms:
        type: string
        required: false
        default: linux/amd64,linux/arm64

jobs:
  build:
    name: Build and Push Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Convert Repository Name to Lowercase
        id: repository_to_lower_case
        run: |
          echo "repo_lower=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        if: ${{ inputs.push }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        id: build-push
        uses: docker/build-push-action@v6
        with:
          cache-from: "ghcr.io/${{ steps.repository_to_lower_case.outputs.repo_lower }}/tools:latest"
          file: docker/Dockerfile
          context: docker
          tags: "ghcr.io/${{ steps.repository_to_lower_case.outputs.repo_lower }}/tools:${{ inputs.tag }}"
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.push }}

      - name: Generate Artifact Attestation
        if: ${{ inputs.push }}
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ steps.repository_to_lower_case.outputs.repo_lower }}
          subject-digest: ${{ steps.build-push.outputs.digest }}
          push-to-registry: true