name: Tools Container - PR Validation

on:
  pull_request:
    paths:
      - 'docker/**'

jobs:
  pr_validation:
    name: PR Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          cache-from: ghcr.io/xenitab/github-actions/tools:latest
          file: docker/Dockerfile
          context: docker
          platforms: linux/amd64,linux/arm64
          push: false
