name: Tools Container - PR Validation

on:
  pull_request:
    paths:
      - 'docker/**'

jobs:
  pr_validation:
    uses: ./.github/workflows/container-build-template.yml
    with:
      push: false
      tag: "pr"