name: '[LITE] Tools Container - Publish Latest'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - '.github/**'

jobs:
  publish_latest:
    name: Push latest [LITE] container image to GitHub Packages
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/shared-steps.yml@afa4bad680ca1bbea899ce1ab3c8668b66f42ac9
    with:
        registry: ghcr.io
        do_tag: 'NOPE'
    secrets: 
      token: ${{ secrets.GITHUB_TOKEN }}
          
