name: 'Tools Container - PR Validation'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'docker/**'

jobs:
  pr_validation:
    name: 'PR Validation'
    uses: ./.github/workflows/shared-steps.yml
    with:
      registry: ghcr.io
      do_tag: 'YES'
