name: '[LITE] Tools Container - PR Validation'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'docker/**'

jobs:
  pr_validation:
    name: '[LITE] PR Validation'
    uses: ./.github/workflows/shared-steps.yml@afa4bad680ca1bbea899ce1ab3c8668b66f42ac9
    with:
      registry: ghcr.io
      do_tag: 'NOPE'
