name: Tools Container - Publish Latest

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - '.github/**'

jobs:
  publish_latest:
    name: Push latest container image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Original 
      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          cache-from: ghcr.io/${{github.repository}}/tools:latest
          file: docker/Dockerfile
          context: docker
          tags: ghcr.io/${{github.repository}}/tools:latest
          push: true

      # Light multiArch image
      - name: '[LITE] Build and push container image'
        uses: docker/build-push-action@v6
        with:
          cache-from: ghcr.io/${{github.repository}}/tools:lite
          file: docker/Dockerfile.lite
          context: docker
          tags: ghcr.io/${{github.repository}}/tools:lite
          platforms: linux/amd64,linux/arm64
          push: true
