name: Tools Container - Publish Tag

on:
  workflow_dispatch:
  release:
    types:
      - published
    paths:
      - "docker/**"
      - ".github/**"

jobs:
  publish_latest:
    name: Push tagged container image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get GitHub Tag
        id: get_tag
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          cache-from: ghcr.io/${{github.repository}}/tools:latest
          file: docker/Dockerfile
          context: docker
          tags: ghcr.io/${{github.repository}}/tools:${{ steps.get_tag.outputs.tag }}
          push: true

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          cache-from: ghcr.io/${{github.repository}}/tools:lite
          file: docker/Dockerfile
          context: docker
          tags: ghcr.io/${{github.repository}}/tools:lite-${{ steps.get_tag.outputs.tag }}
          platforms: linux/amd64,linux/arm64
          push: true
