name: Tools Container - Publish Tag

on:
  release:
    types:
      - published

jobs:
  generate_tag:
    runs-on: ubuntu-latest
    outputs:
      date_tag: ${{ steps.get_date.outputs.date_tag }}
    steps:
      - name: Generate Tag
        id: get_date
        run: |
          date=$(date -u +"%Y.%-m.%-d")
          echo "date_tag=${date}" >> $GITHUB_OUTPUT

  publish_tag:
    needs: generate_tag
    uses: ./.github/workflows/container-build-template.yml
    with:
      push: true
      tag: ${{ needs.generate_tag.outputs.date_tag }}